name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Verify
        run: ./gradlew clean spotlessCheck test integrationTest
